### PR TITLE
docs: Polish README

### LINKED ISSUE #19: Polish README
The documentation stood in the README file, like this issue description, has been written by a typical french guy who strongly need help to make it right.
If a native english dude wants to contribute, s.he would be warmly thanked.

### PR DESCRIPTION
**Pull request by gage117**
Change multiple lines to possibly improve wording

References Issue 19 (Polish README) https://github.com/untemps/svelte-readotron/issues/19

### CODE REVIEW

**Comment by vincentljn** [comment]
Hey! Thanks a lot!
Is there any alternative to the verb `use` I tend to put everywhere?

**Comment by untemps** [comment]
Hey! Thanks a lot!

Is there any alternative to the verb `use` I tend to put everywhere?

**Comment by gage117** [comment]
"Utilize" is the most universal synonym for "use". There are others, they just require an appropriate context to make sense. But I took another look and did reduce the amount of times "use" appears from 7 to 2. Feel free to look at the second commit to see what words I replaced "use" with in each context!

**Comment by untemps** [comment]
That sounds great! Thank you.

**Pull request merged**
